From Stéphane Bryant: improvements in RELOAD dissection
- Follow closely draft-ietf-p2psip-base-18
- Added support for draft-ietf-p2psip-base-18,
  draft-ietf-p2psip-sip-06,
  draft-ietf-p2psip-service-discovery-03,
  draft-ietf-p2psip-self-tuning-04,
  draft-ietf-p2psip-diagnostics-06,
  draft-zong-p2psip-drr-00,
- Handoff to the xml dissectors for
  configuration data
- export the message content dissection function
  in the new packet-reload.h file for use in
  related protocols (draft-hautakorpi-p2psip-with-hip-01)

https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=6317

From me:
- Fix a few C++ style comments;
- Fix:
packet-reload.c(2156) ... conversion from 'guint64' to 'guint32', possible loss of data
packet-reload.c(3528) ... conversion from 'guint64' to 'guint32', possible loss of data

Note: Additional fix yet req'd since checkhf.pl gives:
  ERROR: NO ARRAY: packet-reload.c, hf_reload_dmflag_underlay_hop
  Unused entry: packet-reload.c, hf_reload_storeddata_signature
  Unused entry: packet-reload.c, hf_reload_storeddataspecifiers

(Compile is OK).


git-svn-id: http://anonsvn.wireshark.org/wireshark/trunk@39301 f5534014-38df-0310-8fa8-9805f1628bb7