Fix In file included from export_dissection_dialog.cpp:24:0: export_dissection_dialog.h:66:34: error: field 'export_type_map_' has incomplete type export_dissection_dialog.cpp: In constructor 'ExportDissectionDialog::ExportDissectionDialog(QWidget*, capture_file*, export_type_e)': export_dissection_dialog.cpp:80:5: error: 'export_type_map_' was not declared in this scope export_dissection_dialog.cpp: In member function 'void ExportDissectionDialog::exportTypeChanged(QString)': export_dissection_dialog.cpp:214:20: error: 'export_type_map_' was not declared in this scope
Missing <QMap> include in export_disssection_dialog.h (in my Ubuntu Box with Qt 4.7.4 ?)

git-svn-id: http://anonsvn.wireshark.org/wireshark/trunk@45574 f5534014-38df-0310-8fa8-9805f1628bb7